language: node_js
node_js:
  - "14"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
  - npm install
  - pip install -r requirements.txt
script:
  - truffle test
  - npm test
